version: 0.2

env:
  variables:
    IMAGE_NAME: quarkus-app
    DOCKERFILE_PATH: src/main/docker/Dockerfile.jvm
    AWS_REGION: us-east-1
    ECR_REPO_URL: 311964230334.dkr.ecr.us-east-1.amazonaws.com
    EC2_INSTANCE_ID: i-0e0d5c37103a5f81c

phases:
  install:
    runtime-versions:
      java: corretto17
      docker: 20
    commands:
      - echo Instalando dependencias...
      - yum install -y git
  pre_build:
    commands:
      - echo Compilando el proyecto...
      - ./mvnw clean package -DskipTests
      - echo Iniciando sesión en Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URL
  build:
    commands:
      - echo Construyendo imagen Docker...
      - docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME:latest $ECR_REPO_URL/$IMAGE_NAME:latest
  post_build:
    commands:
      - echo Subiendo imagen a Amazon ECR...
      - docker push $ECR_REPO_URL/$IMAGE_NAME:latest
      - echo Desplegando en EC2 con SSM...
      - aws ssm send-command \
        --document-name "AWS-RunShellScript" \
        --comment "Despliegue Quarkus" \
        --instance-ids "$EC2_INSTANCE_ID" \
        --region "$AWS_REGION" \
        --parameters commands="docker pull $ECR_REPO_URL/$IMAGE_NAME:latest && docker stop $IMAGE_NAME || true && docker rm $IMAGE_NAME || true && docker run -d --name $IMAGE_NAME -p 8080:8080 $ECR_REPO_URL/$IMAGE_NAME:latest"
